### ISSUE TITLE
External API changes in 3.0.0 are not reflected in the .so -version-info

### ISSUE THREAD

**Issue by bprotopopov** [SpectraLogic/ds3_c_sdk#152]
The APIs have changed since 1.2.0, yet the -version-info is still 0.0.0 (see src/Makefile.am). This seems like a bug to me.

**Comment by bprotopopov** [comment]
I would recommend updating the version info to 1.0.0 to reflect incompatible API changes if any.

**Comment by DenverM80** [comment]
Thank you for the feedback - the Makefile.am -version-info has been updated.

https://github.com/SpectraLogic/ds3_c_sdk/pull/156
