### ISSUE TITLE
Memory error after "Request encountered a 307 redirect"

### ISSUE THREAD

**Issue by omvolkov** [SpectraLogic/ds3_c_sdk#229]
The function **net_process_request** in the file "ds3_net.c" does not handle the condition "Request encountered a 307 redirect" correctly most often resulting in the crash "double free or corruption". The call `g_free(url)` before checking that condition frees a pointer `url`, and the `continue` statement transfers control to the next iteration of `while (retry_count < client->num_redirects)` loop where the calls `curl_easy_setopt(handle, CURLOPT_URL, url)` and `g_free(url)` access a freed `url`.

This is a code fragment that handles a 307 redirect (with added comments indicating the problem):

```
g_free(url);       // *** Frees 'url'.

if (response_data.status_code == 307) {
    ds3_log_message(client->log, DS3_INFO, "Request encountered a 307 redirect");

   retry_count++;
   ds3_log_message(client->log, DS3_DEBUG, "Retry Attempt: %d | Max Retries: %d", retry_count, client->num_redirects);

   if (retry_count == client->num_redirects) {
       ds3_str_free(error->message);
       error->message = ds3_str_init("Encountered too many redirects while attempting to fulfill the request");
       error->code = DS3_ERROR_TOO_MANY_REDIRECTS;
   } else {
       continue;  // *** Continues to using a freed 'url'.
   }
}
```

**Comment by shabtaisharon** [comment]
Hello @omvolkov! Thank you for filing this issue, it sounds like you are on top of the issue and a potential solution, feel free to make an open-source contribution, we'll appreciate your contribution.

**Comment by omvolkov** [comment]
Hello @shabtaisharon, the complexity of a potential solution depends on whether or not a 307 Temporary Redirect response specifies to repeat a request to the same or a different URL.

According to the commit [https://github.com/SpectraLogic/ds3_c_sdk/commit/06581a2f49d2908b89a45760029c79aed1dad20f](https://github.com/SpectraLogic/ds3_c_sdk/commit/06581a2f49d2908b89a45760029c79aed1dad20f) made to resolve #41, the library always repeats the request to the same URL. If this is correct behavior, I can provide a fix for the issue I opened.

**Comment by shabtaisharon** [comment]
Hi @omvolkov, you can assume that the commit made by @rpmoore back in 2015 is the correct behavior, and provide a fix depends on that.
